---
- name: install packages
  ansible.builtin.apt:
    name:
      # - nginx-block-ai-bots
      - nginx-light
    state: present

- ansible.builtin.file:
    path: /etc/nginx/modules-enabled/50-mod-http-echo.conf
    state: absent
  notify: restart nginx

- name: enable and start service
  ansible.builtin.systemd_service:
    name: nginx.service
    enabled: true
    state: started
