---
- name: install packages
  ansible.builtin.apt:
    name:
      - imapfilter
      - ripmime
    state: present

- name: configure service template
  ansible.builtin.template:
    src: imapfilter.service.j2
    dest: /etc/systemd/system/imapfilter@.service
    owner: root
    group: root
    mode: !!str 0444
    # validate: systemd-analyze verify %s
  notify: restart imapfilter

- name: enable and start service
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: imapfilter@{{ imapfilter_item }}.service
    enabled: true
    state: started
  loop: "{{ imapfilter_users }}"
  loop_control:
    loop_var: imapfilter_item
