# yamllint disable rule:line-length
---
- name: Gather facts
  hosts: all

  pre_tasks:
    - name: gather facts from excluded hosts
      ansible.builtin.setup: {}
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['all'] }}"
      when: item not in ansible_play_hosts
      run_once: true

    - name: gateway default IPv4 address must be public
      ansible.builtin.assert:
        quiet: true
        that:
          - ([hostvars.gateway.ansible_facts['default_ipv4'].address] | ansible.utils.ipaddr('public')) | length > 0
      run_once: true

- name: Networking
  hosts:
    - os_Archlinux
    - os_Debian
  gather_facts: false

  tasks:
    - when: (systemd_networks | default([])) | length > 0
      block:
        - name: configure network
          ansible.builtin.copy:
            content: "{{ item.content }}"
            dest: /etc/systemd/network/{{ item.name }}.network
            owner: root
            group: root
            mode: !!str 0444
          loop: "{{ systemd_networks }}"
          notify: reboot

        - name: enable systemd-networkd
          ansible.builtin.systemd_service:
            name: systemd-networkd.service
            enabled: true
          notify: reboot

        - name: remove interfaces file
          ansible.builtin.file:
            path: /etc/network/interfaces
            state: absent
          notify: reboot
          when: ansible_facts['os_family'] == 'Debian'

        - name: flush handlers
          ansible.builtin.meta: flush_handlers

        - name: refresh network facts
          ansible.builtin.setup:
            gather_subset:
              - network

  handlers:
    - name: reboot
      ansible.builtin.reboot: {}

- name: Hardening
  hosts:
    - os_Archlinux
    - os_Debian
  gather_facts: false

  roles:
    - role: hardening

  handlers:
    - name: reboot
      ansible.builtin.reboot: {}

- name: Set up OwnCA
  hosts: localhost
  gather_facts: false

  roles:
    - name: ownca

- name: Configure Gateway
  hosts: gateway
  gather_facts: false

  roles:
    - role: ctrld

- name: Configure Tombstone
  hosts:
    - tombstone
  gather_facts: false

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml

  pre_tasks:
    - name: install open-iscsi
      ansible.builtin.apt:
        name:
          - btrfs-progs
          - open-iscsi
        install_recommends: false
        state: present
      notify: reboot

    - name: enable and start service
      ansible.builtin.systemd_service:
        name: open-iscsi.service
        enabled: true
        state: started

    - name: install prerequisite packages
      ansible.builtin.apt:
        name:
          - acl
          - attr
          - gpg
          - python3-demjson # jsonlint
          - python3-lxml
          - virtualenv
          - yamllint

    - name: remove conflicting packages
      ansible.builtin.apt:
        name:
          - ufw
        autoremove: true
        purge: true
        state: absent

  roles:
    - role: alertmanager
      when: false # TODO
    - role: alloy
      when: false # FIXME
    - role: bazarr
    - role: beszel
      vars:
        beszel_hub: true
    - role: calibre
      when: false # TODO
    - role: calibre_web
      when: false # TODO
    - role: chrony
    - role: fluxcd
    - role: homebridge
    - role: imapfilter
    - role: kubernetes
    - role: lidarr
      when: false
    - role: nzbget
      when: false
    - role: ombi
      when: false
    - role: opensmtpd
    - role: prowlarr
      when: false
    - role: radarr
      when: false
    - role: readarr
      when: false # TODO
    - role: restic
      when: false # TODO
    - role: sonarr
      when: false
    - role: sshd
    - role: unattended_upgrades
    - role: unbound

  tasks:
    - name: install additional packages
      ansible.builtin.apt:
        name:
          # - cpupower
          - curl
          - jq
          # - linux-cpupower
          - lm-sensors
          - lsof
          # - man-db
          - net-tools
          - rfkill
          - tcpdump

    - name: remove unwanted packages
      ansible.builtin.apt:
        autoremove: true
        name:
          - nano
        purge: true
        state: absent

    # - name: disable unused hardware
    #   ansible.builtin.copy:
    #     content: |
    #       blacklist btusb
    #       blacklist snd_hda_intel
    #     dest: /etc/modprobe.d/blacklist.conf
    #     owner: root
    #     group: root
    #     mode: !!str 0444
    #   notify:
    #     - update-initramfs
    #     - reboot

  handlers:
    # - name: update-initramfs
    #   ansible.builtin.command:
    #     argv:
    #       - mkinitcpio
    #       - -P

    - name: reboot
      ansible.builtin.reboot: {}

    - name: restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd.service
        state: restarted

    - name: update-grub
      ansible.builtin.command:
        argv:
          - update-grub

- name: Configure DiskStation
  hosts:
    - diskstation
  gather_facts: false

  module_defaults:
    community.docker.docker_compose_v2:
      docker_cli: /usr/local/bin/docker

  pre_tasks:
    - name: install Python
      ansible.builtin.raw: /usr/syno/bin/synopkg install_from_server Python3.9
      changed_when: false
      failed_when: false

    - name: bootstrap pip
      # ansible.builtin.raw: /usr/local/bin/python3.9 -m ensurepip --upgrade
      ansible.builtin.raw: /usr/local/bin/python3.9 -m ensurepip
      changed_when: false

    - name: bootstrap Python dependencies
      # ansible.builtin.raw: /usr/local/bin/python3.9 -m pip install --upgrade packaging setuptools
      ansible.builtin.raw: /usr/local/bin/python3.9 -m pip install packaging setuptools
      changed_when: false

    - name: install Python dependencies
      ansible.builtin.pip:
        name:
          - PyYAML
          - requests

    - ansible.builtin.copy:
        src: "{{ playbook_dir~'/ownca/root-ca.crt' }}"
        dest: /var/db/ca-certificates/OwnCA.crt
        owner: root
        group: root
        mode: !!str 0444
      notify: update CA certificates

  roles:
    - role: beszel
      when: false

  handlers:
    - name: update CA certificates
      shell: /usr/syno/bin/update-ca-certificates.sh

- name: Configure Vegas
  hosts:
    - vegas
  gather_facts: false

  pre_tasks:
    - name: install open-iscsi
      ansible.builtin.pacman:
        name:
          - btrfs-progs
          - open-iscsi
        state: present
      notify: reboot

    - delegate_to: tombstone
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/agent-token
      register: result

    - ansible.builtin.set_fact:
        k3s_token: "{{ result.content | b64decode }}"

  roles:
    - role: beszel
    - name: kubernetes

  handlers:
    - name: reboot
      ansible.builtin.reboot: {}
