# yamllint disable rule:line-length
---
- name: Gather facts
  hosts: all

  pre_tasks:
    - name: gather facts from excluded hosts
      ansible.builtin.setup: {}
      delegate_to: "{{ item }}"
      delegate_facts: true
      loop: "{{ groups['all'] }}"
      when: item not in ansible_play_hosts
      run_once: true
      tags:
        - always

    - name: gateway default IPv4 address must be public
      ansible.builtin.assert:
        quiet: true
        that:
          - ([hostvars.gateway.ansible_facts['default_ipv4'].address] | ansible.utils.ipaddr('public')) | length > 0
      run_once: true
      tags:
        - always

- name: Set up OwnCA
  hosts: localhost
  gather_facts: false

  roles:
    - name: ownca
      tags:
        - always

- name: Configure Gateway
  hosts: gateway
  gather_facts: false

  roles: []

- name: Configure Tombstone
  hosts:
    - tombstone
  gather_facts: false

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: /etc/rancher/k3s/k3s.yaml

  pre_tasks:
    - name: configure LAN network
      ansible.builtin.copy:
        content: |
          [Match]
          Name={{ lan_if }}

          [Network]
          Address={{ lan_ipv4_address }}/24
          DNS={{ lan_ipv4_subnet | ansible.utils.nthhost(1) }}
          Gateway={{ lan_ipv4_subnet | ansible.utils.nthhost(1) }}
          IPv6AcceptRA=yes
          IPv6PrivacyExtensions=yes

          [IPv6AcceptRA]
          Token=eui64
        dest: /etc/systemd/network/20-ethernet.network
        owner: root
        group: root
        mode: !!str 0444
      notify: reboot
      tags:
        - always

    - name: enable systemd-networkd
      ansible.builtin.systemd_service:
        name: systemd-networkd.service
        enabled: true
      notify: reboot
      tags:
        - always

    - name: remove interfaces file
      ansible.builtin.file:
        path: /etc/network/interfaces
        state: absent
      notify: reboot
      tags:
        - always

    - name: flush handlers
      ansible.builtin.meta: flush_handlers
      tags:
        - always

    - name: refresh network facts
      ansible.builtin.setup:
        gather_subset:
          - network
      tags:
        - always

    - name: install open-iscsi
      ansible.builtin.apt:
        name:
          - btrfs-progs
          - open-iscsi
        install_recommends: false
        state: present
      notify: reboot
      tags:
        - always

    - name: enable and start service
      ansible.builtin.systemd_service:
        name: open-iscsi.service
        enabled: true
        state: started

    - name: install prerequisite packages
      ansible.builtin.apt:
        name:
          - acl
          - attr
          - gpg
          - python3-demjson # jsonlint
          - python3-lxml
          - virtualenv
          - yamllint
      tags:
        - always

    - name: remove conflicting packages
      ansible.builtin.apt:
        name:
          - ufw
        autoremove: true
        purge: true
        state: absent
      tags:
        - always

  roles:
    - role: alertmanager
      tags:
        - alertmanager
      when: false # TODO
    - role: alloy
      tags:
        - alloy
      when: false # FIXME
    - role: bazarr
      tags:
        - bazarr
      when: false # TODO
    - role: beszel
      tags:
        - beszel
      vars:
        beszel_hub: true
    - role: calibre
      tags:
        - calibre
      when: false # TODO
    - role: calibre_web
      tags:
        - calibre-web
      when: false # TODO
    - role: chrony
      tags:
        - chrony
    - role: fluxcd
      tags:
        - fluxcd
    - role: forgejo
      tags:
        - forgejo
      when: false # TODO
    - role: homebridge
      tags:
        - homebridge
    - role: imapfilter
      tags:
        - imapfilter
      when: false # TODO
    - role: kubernetes
      tags:
        - kubernetes
    - role: lidarr
      tags:
        - lidarr
    - role: nftables
      tags:
        - nftables
    - role: nzbget
      tags:
        - nzbget
    - role: ombi
      tags:
        - ombi
    - role: open_telemetry
      tags:
        - open-telemetry
    - role: opensmtpd
      tags:
        - opensmtpd
    - role: prowlarr
      tags:
        - prowlarr
    - role: radarr
      tags:
        - radarr
    - role: readarr
      tags:
        - readarr
      when: false # TODO
    - role: restic
      tags:
        - restic
      when: false # TODO
    - role: samba
      tags:
        - samba
    - role: sonarr
      tags:
        - sonarr
    - role: sops
      tags:
        - sops
    - role: sshd
      tags:
        - sshd
    - role: tdarr
      tags:
        - tdarr
      when: false # TODO
    - role: unattended_upgrades
      tags:
        - unattended-upgrades
    - role: unbound
      tags:
        - unbound

  tasks:
    - name: install additional packages
      ansible.builtin.apt:
        name:
          # - cpupower
          - curl
          - jq
          # - linux-cpupower
          - lm-sensors
          - lsof
          # - man-db
          - net-tools
          - rfkill
          - tcpdump
      tags:
        - always

    - name: remove unwanted packages
      ansible.builtin.apt:
        autoremove: true
        name:
          - nano
        purge: true
        state: absent
      tags:
        - always

    # - name: disable unused hardware
    #   ansible.builtin.copy:
    #     content: |
    #       blacklist btusb
    #       blacklist snd_hda_intel
    #     dest: /etc/modprobe.d/blacklist.conf
    #     owner: root
    #     group: root
    #     mode: !!str 0444
    #   notify:
    #     - update-initramfs
    #     - reboot
    #   tags:
    #     - always

  handlers:
    # - name: update-initramfs
    #   ansible.builtin.command:
    #     argv:
    #       - mkinitcpio
    #       - -P

    - name: reboot
      ansible.builtin.reboot: {}

    - name: restart systemd-networkd
      ansible.builtin.systemd:
        name: systemd-networkd.service
        state: restarted

    - name: update-grub
      ansible.builtin.command:
        argv:
          - update-grub

- name: Configure DiskStation
  hosts:
    - diskstation
  gather_facts: false

  pre_tasks:
    - name: install Python
      ansible.builtin.raw: /usr/syno/bin/synopkg install_from_server Python3.9
      changed_when: false
      failed_when: false

    - name: bootstrap pip
      # ansible.builtin.raw: /usr/local/bin/python3.9 -m ensurepip --upgrade
      ansible.builtin.raw: /usr/local/bin/python3.9 -m ensurepip
      changed_when: false

    - name: bootstrap Python dependencies
      # ansible.builtin.raw: /usr/local/bin/python3.9 -m pip install --upgrade packaging setuptools
      ansible.builtin.raw: /usr/local/bin/python3.9 -m pip install packaging setuptools
      changed_when: false

    - name: install Python dependencies
      ansible.builtin.pip:
        name:
          - PyYAML
          - requests

  roles:
    - role: beszel
      tags:
        - beszel
      when: false

- name: Configure Vegas
  hosts:
    - vegas
  gather_facts: false

  pre_tasks:
    - name: install open-iscsi
      ansible.builtin.pacman:
        name:
          - btrfs-progs
          - open-iscsi
        state: present
      notify: reboot
      tags:
        - always

    - delegate_to: tombstone
      ansible.builtin.slurp:
        src: /var/lib/rancher/k3s/server/agent-token
      register: result
      tags:
        - kubernetes

    - ansible.builtin.set_fact:
        k3s_token: "{{ result.content | b64decode }}"
      tags:
        - kubernetes

  roles:
    - role: beszel
      tags:
        - beszel
    - name: kubernetes
      tags:
        - kubernetes

  handlers:
    - name: reboot
      ansible.builtin.reboot: {}
