---
- name: create group
  ansible.builtin.group:
    name: pds
    system: true

- name: create user
  ansible.builtin.user:
    comment: Personal Data Server
    create_home: false
    group: pds
    home: /srv/pds
    name: pds
    shell: "{{ nologin_shell }}"
    system: true

- name: create data directory
  ansible.builtin.file:
    path: "{{ pds_item }}"
    owner: pds
    group: pds
    mode: !!str 0700
    state: directory
  loop:
    - /srv/pds
    # - /srv/pds/git
    # - /srv/pds/git/.ssh
    # - /srv/pds/pds
    # - /srv/pds/pds/conf
  loop_control:
    loop_var: pds_item
