{
 "title": "Unbound Statistics",
 "description": "A simple dashboard for showing the output from the Unbound exporter (https://github.com/kumina/unbound_exporter)",
 "tags": [
  "prometheus",
  "unbound"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Total queries",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(unbound_queries_total{instance=\"127.0.0.1:9167\"})"
    }
   ]
  },
  {
   "title": "Total queries per second",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "reqps",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(irate(unbound_queries_total{instance=\"127.0.0.1:9167\"}[5m]))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "unbound_time_up_seconds_total{instance=\"127.0.0.1:9167\"}"
    }
   ]
  },
  {
   "title": "Total queries by thread",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_queries_total[5m])",
     "legendFormat": "{{thread}}"
    }
   ]
  },
  {
   "title": "Cache sizes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "unbound_memory_caches_bytes", "legendFormat": "{{cache}}" },
    { "expr": "unbound_memory_modules_bytes\n", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Qureries by type",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "\nirate(unbound_query_types_total[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Qureries by class",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_query_classes_total[5m])",
     "legendFormat": "{{class}}"
    }
   ]
  },
  {
   "title": "Response time heatmap",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(unbound_response_time_seconds_bucket{instance=\"127.0.0.1:9167\",job=\"unbound\",le=~\"0.001024|0.002048|0.004096|0.008192|0.016384|0.032768|0.065536|0.131072|0.262144|0.524288|1|2|4|8|16|32|64\"}[5m])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Answers by rcode",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "irate(unbound_answer_rcodes_total[5m])",
     "legendFormat": "{{rcode}}"
    }
   ]
  }
 ]
}