# yamllint disable rule:line-length
---
- name: restart k3s
  ansible.builtin.systemd_service:
    name: "{{ kubernetes_control_plane | ansible.builtin.ternary('k3s-server', 'k3s') }}.service"
    daemon_reload: true
    state: restarted
