# yamllint disable rule:line-length
---
- name: create cert-manager namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: &namespace cert-manager

- name: create ownca intermediate CA secret
  kubernetes.core.k8s:
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        labels:
          app.kubernetes.io/managed-by: Ansible
        name: ownca-intermediate-ca
        namespace: *namespace
      stringData:
        tls.crt: "{{ lookup('file', playbook_dir~'/ownca/intermediate-ca.crt') }}"
        tls.key: "{{ lookup('file', playbook_dir~'/ownca/intermediate-ca.key') }}"
      type: kubernetes.io/tls
