# yamllint disable rule:line-length
---
- ansible.builtin.slurp:
    src: /etc/rancher/k3s/k3s.yaml
  register: kubernetes_kubeconfig_result

- name: "kubeconfig: parse k3s kubeconfig"
  ansible.builtin.set_fact:
    kubernetes_kubeconfig: "{{ kubernetes_kubeconfig_result.content | b64decode | from_yaml }}"

- name: "kubeconfig: ensure local ~/.kube directory exists"
  delegate_to: localhost
  ansible.builtin.file:
    path: ~/.kube
    mode: !!str 0700
    state: directory

- name: "kubeconfig: read existing local kubeconfig"
  delegate_to: localhost
  ansible.builtin.slurp:
    src: ~/.kube/config
  register: kubernetes_kubeconfig_local_file
  failed_when: false

- name: "kubeconfig: set local kubeconfig fact"
  vars:
    empty_kubeconfig:
      apiVersion: v1
      kind: Config
      clusters: []
      contexts: []
      users: []
      current-context: ""
  ansible.builtin.set_fact:
    kubernetes_local_kubeconfig: "{{ (kubernetes_kubeconfig_local_file.content | b64decode | from_yaml) if kubernetes_kubeconfig_local_file.content is defined else empty_kubeconfig }}"

- name: "kubeconfig: build merged kubeconfig"
  ansible.builtin.set_fact:
    kubernetes_merged_kubeconfig:
      apiVersion: v1
      kind: Config
      clusters: "{{ (kubernetes_local_kubeconfig.clusters | rejectattr('name', 'equalto', kubernetes_cluster_name) | list) + [kubernetes_kubeconfig_cluster] }}"
      contexts: "{{ (kubernetes_local_kubeconfig.contexts | rejectattr('name', 'equalto', kubernetes_cluster_name) | list) + [kubernetes_kubeconfig_context] }}"
      current-context: "{{ kubernetes_local_kubeconfig['current-context'] | default('', true) }}"
      users: "{{ (kubernetes_local_kubeconfig.users | rejectattr('name', 'equalto', kubernetes_cluster_name) | list) + [kubernetes_kubeconfig_user] }}"
  vars:
    kubernetes_kubeconfig_cluster:
      name: "{{ kubernetes_cluster_name }}"
      cluster: "{{ kubernetes_kubeconfig.clusters[0].cluster }}"
    kubernetes_kubeconfig_context:
      name: "{{ kubernetes_cluster_name }}"
      context:
        cluster: "{{ kubernetes_cluster_name }}"
        user: "{{ kubernetes_cluster_name }}"
    kubernetes_kubeconfig_user:
      name: "{{ kubernetes_cluster_name }}"
      user: "{{ kubernetes_kubeconfig.users[0].user }}"

- name: "kubeconfig: write merged kubeconfig"
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ kubernetes_merged_kubeconfig | to_nice_yaml(indent=2) }}"
    dest: ~/.kube/config
    mode: !!str 0600
