# yamllint disable rule:line-length
---
- name: install prerequisites
  when: kubernetes_control_plane
  block:
    - ansible.builtin.apt:
        name: python3-kubernetes
        install_recommends: false
        state: present
      when: ansible_facts['os_family'] == 'Debian'

    - community.general.pacman:
        name: python-kubernetes
        state: present
      when: false # ansible_facts['os_family'] == 'Archlinux'

- ansible.builtin.include_tasks:
    file: nvidia-container-toolkit.yml
  when: "'nvidia.com/gpu.present=true' in kubernetes_node_labels"

- ansible.builtin.include_tasks:
    file: k3s.yml

- ansible.builtin.include_tasks:
    file: kubeconfig.yml
  when: kubernetes_control_plane

- ansible.builtin.include_tasks:
    file: cert-manager.yml
  when: kubernetes_control_plane
