---
- name: create data directory
  ansible.builtin.file:
    path: /var/lib/bazarr
    owner: root
    group: "{{ library_group }}"
    mode: !!str 0750
    state: directory

- name: create data directories
  ansible.builtin.file:
    path: /var/lib/bazarr/{{ bazarr_item }}
    owner: "{{ library_user }}"
    group: "{{ library_group }}"
    mode: !!str 0700
    state: directory
  loop:
    - backup
    - cache
    - config
    - db
    - log
    - restore
  loop_control:
    loop_var: bazarr_item

# - name: create library directories
#   ansible.builtin.file:
#     path: "{{ library_path }}/{{ bazarr_item }}"
#     owner: "{{ library_user }}"
#     group: "{{ library_group }}"
#     mode: !!str 2770
#     state: directory
#   loop:
#     - backups/bazarr
#     - media/movies
#     - torrents/complete
#     - torrents/complete/bazarr
#     - usenet/complete
#     - usenet/complete/bazarr
#     - usenet/incomplete # strange but true
#   loop_control:
#     loop_var: bazarr_item
