FROM amd64/alpine:3.10.3

RUN apk add --no-cache \
		drill=1.7.0-r2 \
		tzdata=2019c-r0 \
		unbound=1.9.1-r7 \
	&& cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime \
	&& echo '{{ timezone }}' >/etc/timezone \
	&& apk del --no-cache --purge tzdata

EXPOSE 53

# HEALTHCHECK --interval=5s --timeout=3s --start-period=5s CMD drill @127.0.0.1 cloudflare.com || exit 1

CMD ["/usr/sbin/unbound"]
