FROM alpine:3.12

RUN apk add --no-cache \
		tzdata=2020a-r0 \
		unbound=1.10.1-r0 \
	&& cp '/usr/share/zoneinfo/{{ timezone }}' /etc/localtime \
	&& echo '{{ timezone }}' >/etc/timezone \
	&& apk del --no-cache --purge tzdata

EXPOSE 53/tcp 53/udp

CMD ["/usr/sbin/unbound"]
