FROM alpine:3.12.0

RUN apk add --no-cache \
		drill=1.7.1-r1 \
		tzdata=2020a-r0 \
		unbound=1.10.1-r0 \
	&& cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime \
	&& echo '{{ timezone }}' >/etc/timezone \
	&& apk del --no-cache --purge tzdata

EXPOSE 53

# HEALTHCHECK --interval=5s --timeout=3s --start-period=5s CMD drill @127.0.0.1 cloudflare.com || exit 1

CMD ["/usr/sbin/unbound"]
