---
- name: create namespace
  kubernetes.core.k8s:
    apply: true
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: opentelemetry
    server_side_apply:
      field_manager: ansible

- kubernetes.core.k8s:
    apply: true
    namespace: opentelemetry
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        labels:
          app.kubernetes.io/managed-by: Ansible
          reconcile.fluxcd.io/watch: Enabled
        name: uptrace
      stringData:
        dsn: "{{ uptrace_dsn }}"
      type: Opaque
    server_side_apply:
      field_manager: ansible
