FROM alpine:3.12

COPY pvr /etc/periodic/hourly/pvr

RUN chmod 755 /etc/periodic/hourly/pvr \
	&& apk add --no-cache \
		ffmpeg=4.3.1-r0 \
		perl=5.30.3-r0 \
		perl-cgi=4.47-r0 \
		perl-json=4.02-r0 \
		perl-lwp-protocol-https=6.07-r1 \
		perl-mojolicious=8.50-r0 \
		perl-xml-libxml=2.0205-r0 \
		tzdata=2020a-r0 \
	&& cp '/usr/share/zoneinfo/{{ timezone }}' /etc/localtime \
	&& echo '{{ timezone }}' >/etc/timezone \
	&& apk del --no-cache --purge tzdata \
	&& apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \
		atomicparsley=0.9.6-r1 \
	&& wget https://github.com/get-iplayer/get_iplayer/archive/v{{ get_iplayer_version }}.tar.gz \
	&& tar -xzf v{{ get_iplayer_version }}.tar.gz \
	&& rm v{{ get_iplayer_version }}.tar.gz \
	&& chmod 755 get_iplayer-{{ get_iplayer_version }}/get_iplayer \
	&& mv get_iplayer-{{ get_iplayer_version }}/get_iplayer /usr/bin/ \
	&& rm -r get_iplayer-{{ get_iplayer_version }}

CMD ["/usr/sbin/crond", "-f"]
