FROM amd64/alpine:3.10.3

RUN apk add --no-cache \
		nodejs=10.16.3-r0 \
		npm=10.16.3-r0 \
		tzdata=2019c-r0 \
	&& cp /usr/share/zoneinfo/{{ timezone }} /etc/localtime \
	&& npm set global-style=true \
	&& npm set package-lock=false \
	&& npm install -g --unsafe-perm \
		homebridge@0.4.50 \
		homebridge-bravia \
		homebridge-unifi-occupancy-sensor \
	&& mkdir /homebridge

VOLUME /homebridge

CMD ["/usr/bin/homebridge", "--no-qrcode", "--remove-orphans", "--user-storage-path", "/homebridge"]
